export GOOGLE_APPLICATION_CREDENTIALS="~/.ssh/tensorflow-serving-40618fd23e48.json"
export BUCKET_NAME="gs://tensorflow-serving-200405-2"
export PROJECT_ID="tensorflow-serving-200405"
export REGION="us-central1"
export MODEL_NAME="census_dist_1_$(date '+%d_%m_%Y_%H_%M_%S')"
export JOB_NAME="${MODEL_NAME}"
